language: haskell
ghc: 7.8

branches:
  only:
    - source

sudo: false

cache:
  directories:
    - .cabal-sandbox

env:
  global:
    -   secure: "WsWzMk3XoM3rS+QOt2IGzAGE5H36pkXcdsZ62UaCjI9P7/XjANt2/NwWSb+1AxL70EFg1AG5fulFIka+jgftsCAKB7zuVKu//M1mCpKsoG+zsSB+ZyuHNTmLwdz0lnmYFb2bTrUQAEMcUcA/wGizIoaDNhHE+1Y2J46bxGzRGEA="

install:
  - cabal sandbox init
  - cabal install -j hakyll
  - ghc --make site.hs

before_script:
  - cd _site
  - git checkout master
  - git pull origin master
  - cd ..

script: ./site build

after_script:
  - cd _site
  - git status
  - git add --all
  - git config --global user.email "travis@ogion.cz"
  - git config --global user.name "Travis"
  - git commit -m "snapshot $(date '+%m/%d/%y %H:%M')"
  - git push "$REPO_URL" master | grep -v http
  - cd ..

